// Every visible word on a card is generated by these two functions, and this is
// the code that has quietly lied twice — once about a Threat's Clear value,
// once about an Omen's Menace. Both times a test would have caught it.

import { describe, it, expect } from 'vitest';
import { ALL_CARDS, card } from '../content/cards';
import { opsFor } from '../engine/effects';
import { describeOps, cardKeywords, thirdLine } from '../client/src/cardText';
import { GLOSSARY } from '../client/src/glossaryData';

describe('rules text', () => {
  it('describes every op the content actually uses', () => {
    // The `default` branch prints the raw op name, which reaches the table as
    // something like "gritNextTurn". Anything new must be given words.
    const raw: string[] = [];
    for (const c of ALL_CARDS) {
      for (const fev of [false, true]) {
        if (fev && !c.fevered) continue;
        for (const op of opsFor(c, fev)) {
          const text = describeOps([op]);
          if (text === op.op) raw.push(`${c.name}: ${op.op}`);
        }
      }
      for (const extra of [c.bounty, c.toll]) {
        for (const op of extra ?? []) {
          if (describeOps([op]) === op.op) raw.push(`${c.name}: ${op.op}`);
        }
      }
    }
    expect(raw).toEqual([]);
  });

  it('never leaves a card with nothing to say', () => {
    for (const c of ALL_CARDS) {
      const words = describeOps(opsFor(c, false));
      // A Threat has no ops by design and carries its flavour instead.
      const silent = words === '' && !c.passive;
      const isThreat = ['trouble', 'mythos', 'omen', 'scar', 'kit'].includes(c.type);
      if (silent) expect(isThreat, `${c.name} says nothing`).toBe(true);
    }
  });
});

describe('what a card explains when you look closely', () => {
  it('explains at least one thing about every card', () => {
    for (const c of ALL_CARDS) {
      expect(cardKeywords(c, false).length, c.name).toBeGreaterThan(0);
    }
  });

  it('only ever names terms the glossary actually has', () => {
    // `cardKeywords` silently drops an unknown key, so a typo would simply
    // stop explaining something and never say so.
    const seen = new Set<string>();
    for (const c of ALL_CARDS) {
      for (const fev of [false, true]) {
        if (fev && !c.fevered) continue;
        for (const k of cardKeywords(c, fev)) seen.add(k);
      }
    }
    for (const k of seen) expect(GLOSSARY[k], k).toBeDefined();
    // And it is actually reaching a good spread of the glossary, not two terms.
    expect(seen.size).toBeGreaterThan(10);
  });

  it('explains the marks that are drawn on that particular card', () => {
    const colt = cardKeywords(card('colt'), false);
    expect(colt).toContain('signs');      // it is a Sign
    expect(colt).toContain('whispers');   // it carries Whisper pips
    expect(colt).toContain('grit');       // it has a coin value
    expect(colt).toContain('threat');     // "Destroy a Threat"

    const omen = cardKeywords(card('dead-cattle'), false);
    expect(omen).toContain('omen');
    expect(omen).toContain('menace');     // Omens print 0 and menace anyway

    // A turned Sign explains the Turning, and itself as Fevered.
    const turned = cardKeywords(card('colt'), true);
    expect(turned).toContain('fevered');
    expect(turned).toContain('turning');
  });
});


describe('the third line', () => {
  /**
   * DESIGN.md §7 gives a Threat three lines: Clear, Menace, and a Bounty in
   * Act I or a Toll in Act II. The third one was never drawn, so nine Trouble
   * cards paid a reward nobody could see and the two Tolls advertised no price.
   */
  it('prints the Bounty on every Act I Threat that pays one', () => {
    const paying = ALL_CARDS.filter((c) => c.bounty?.length);
    expect(paying.length).toBeGreaterThan(5);
    for (const c of paying) {
      expect(thirdLine(c, false), c.name).toMatch(/^Bounty: /);
    }
  });

  it('prints the Toll on a Threat that cannot be cleared', () => {
    const priced = ALL_CARDS.filter((c) => c.toll?.length);
    expect(priced.length).toBeGreaterThan(0);
    for (const c of priced) {
      expect(thirdLine(c, false), c.name).toContain('Toll: ');
      // A Toll only exists because damage cannot remove the thing.
      expect(c.clear, c.name).toBeUndefined();
    }
  });

  it('leaves an ordinary card saying only what it does', () => {
    // Damage now names what it hits — the Colt reads "4 damage to a Threat"
    // rather than a bare number, which is also where the `threat` glossary
    // keyword comes from now that it no longer says "Destroy".
    expect(thirdLine(card('winchester'), false)).toBe('2 damage to a Threat');
    expect(thirdLine(card('saddlebag'), false)).toBe('');
  });

  it('counts a repeated reward instead of repeating it', () => {
    // Cattle Baron's Men pays two Provisions and read "Take a Provision free ·
    // Take a Provision free", which is easy to misread as one reward described
    // twice.
    expect(thirdLine(card('barons-men'), false))
      .toBe('Bounty: Take a Provision free ×2');
  });

  it('explains Bounty and Toll when the card is looked at closely', () => {
    expect(cardKeywords(card('barons-men'), false)).toContain('bounty');
    const choir = cardKeywords(card('dry-grass'), false);
    expect(choir).toContain('toll');
    expect(choir).toContain('scars');
  });
});
