// Every visible word on a card is generated by these two functions, and this is
// the code that has quietly lied twice — once about a Threat's Clear value,
// once about an Omen's Menace. Both times a test would have caught it.

import { describe, it, expect } from 'vitest';
import { ALL_CARDS, SIGN_IDS, card } from '../content/cards';
import { opsFor } from '../engine/effects';
import { describeOps, cardKeywords, thirdLine } from '../client/src/cardText';
import { GLOSSARY } from '../client/src/glossaryData';

describe('rules text', () => {
  it('describes every op the content actually uses', () => {
    // The `default` branch prints the raw op name, which reaches the table as
    // something like "gritNextTurn". Anything new must be given words.
    const raw: string[] = [];
    for (const c of ALL_CARDS) {
      for (const fev of [false, true]) {
        if (fev && !c.fevered) continue;
        for (const op of opsFor(c, fev)) {
          const text = describeOps([op]);
          if (text === op.op) raw.push(`${c.name}: ${op.op}`);
        }
      }
      for (const extra of [c.bounty, c.toll]) {
        for (const op of extra ?? []) {
          if (describeOps([op]) === op.op) raw.push(`${c.name}: ${op.op}`);
        }
      }
    }
    expect(raw).toEqual([]);
  });

  it('never leaves a card with nothing to say', () => {
    for (const c of ALL_CARDS) {
      const words = describeOps(opsFor(c, false));
      // A Threat has no ops by design and carries its flavour instead.
      const silent = words === '' && !c.passive;
      const isThreat = ['trouble', 'mythos', 'omen', 'scar', 'kit'].includes(c.type);
      if (silent) expect(isThreat, `${c.name} says nothing`).toBe(true);
    }
  });
});

describe('what a card explains when you look closely', () => {
  it('explains at least one thing about every card', () => {
    for (const c of ALL_CARDS) {
      expect(cardKeywords(c, false).length, c.name).toBeGreaterThan(0);
    }
  });

  it('only ever names terms the glossary actually has', () => {
    // `cardKeywords` silently drops an unknown key, so a typo would simply
    // stop explaining something and never say so.
    const seen = new Set<string>();
    for (const c of ALL_CARDS) {
      for (const fev of [false, true]) {
        if (fev && !c.fevered) continue;
        for (const k of cardKeywords(c, fev)) seen.add(k);
      }
    }
    for (const k of seen) expect(GLOSSARY[k], k).toBeDefined();
    // And it is actually reaching a good spread of the glossary, not two terms.
    expect(seen.size).toBeGreaterThan(10);
  });

  it('explains the marks that are drawn on that particular card', () => {
    const colt = cardKeywords(card('colt'), false);
    expect(colt).toContain('signs');      // it is a Sign
    expect(colt).toContain('whispers');   // it carries Whisper pips
    expect(colt).toContain('grit');       // it has a coin value
    expect(colt).toContain('threat');     // "Destroy a Threat"

    const omen = cardKeywords(card('dead-cattle'), false);
    expect(omen).toContain('omen');
    expect(omen).toContain('menace');     // Omens print 0 and menace anyway

    // A turned Sign explains the Turning, and itself as Fevered.
    const turned = cardKeywords(card('colt'), true);
    expect(turned).toContain('fevered');
    expect(turned).toContain('turning');
  });
});


describe('the third line', () => {
  /**
   * DESIGN.md §7 gives a Threat three lines: Clear, Menace, and a Bounty in
   * Act I or a Toll in Act II. The third one was never drawn, so nine Trouble
   * cards paid a reward nobody could see and the two Tolls advertised no price.
   */
  it('prints the Bounty on every Act I Threat that pays one', () => {
    const paying = ALL_CARDS.filter((c) => c.bounty?.length);
    expect(paying.length).toBeGreaterThan(5);
    for (const c of paying) {
      expect(thirdLine(c, false), c.name).toMatch(/^Bounty: /);
    }
  });

  it('prints the Toll on a Threat that cannot be cleared', () => {
    const priced = ALL_CARDS.filter((c) => c.toll?.length);
    expect(priced.length).toBeGreaterThan(0);
    for (const c of priced) {
      expect(thirdLine(c, false), c.name).toContain('Toll: ');
      // A Toll only exists because damage cannot remove the thing.
      expect(c.clear, c.name).toBeUndefined();
    }
  });

  it('leaves an ordinary card saying only what it does', () => {
    // Damage now names what it hits — the Colt reads "4 damage to a Threat"
    // rather than a bare number, which is also where the `threat` glossary
    // keyword comes from now that it no longer says "Destroy".
    expect(thirdLine(card('winchester'), false)).toBe('2 damage to a Threat');
    expect(thirdLine(card('saddlebag'), false)).toBe('');
  });

  it('counts a repeated reward instead of repeating it', () => {
    // Cattle Baron's Men pays two Provisions and read "Take a Provision free ·
    // Take a Provision free", which is easy to misread as one reward described
    // twice.
    expect(thirdLine(card('barons-men'), false))
      .toBe('Bounty: Take a Provision free ×2');
  });

  it('explains Bounty and Toll when the card is looked at closely', () => {
    expect(cardKeywords(card('barons-men'), false)).toContain('bounty');
    const choir = cardKeywords(card('dry-grass'), false);
    expect(choir).toContain('toll');
    expect(choir).toContain('scars');
  });
});

describe('what the market advertises', () => {
  /**
   * A Sign bought in Act II arrives Fevered.
   *
   * `BUY` does `newInstance(def.id, s.act === 'mythos')`, so the shelf showing
   * a clean face after the Turning is advertising a card the shop does not
   * sell. These assert the two faces really are different, which is what makes
   * showing the wrong one a lie rather than a nicety.
   */
  it('a Sign reads differently once it has turned', () => {
    for (const id of SIGN_IDS) {
      const clean = thirdLine(card(id), false);
      const turned = thirdLine(card(id), true);
      const name = card(id).fevered!.name;
      expect(name, `${id} has no Fevered name`).toBeTruthy();
      expect(name).not.toBe(card(id).name);
      // Most also read differently; the Colt is a pure retarget, so its text
      // can legitimately match — the NAME is what always changes.
      expect(typeof clean).toBe('string');
      expect(typeof turned).toBe('string');
    }
  });
});

describe('what "trash" actually does', () => {
  /**
   * Trash is two unrelated rules under one word, and neither was on the card.
   *
   * "In hand" takes your leftmost non-Sign — deterministic and visible, so a
   * player can play around it once told. Damage takes off the top of a
   * shuffled deck, which they cannot. The old text said "Trash 1 of your own"
   * for both, which told them a card would vanish and nothing about which.
   */
  it('names where the card comes from, and which one', () => {
    expect(thirdLine(card('widow'), false))
      .toBe('Trash your leftmost non-Sign in hand');
    // Bad Nerve draws first, then pays.
    expect(thirdLine(card('bad-nerve'), false))
      .toBe('Draw 2 · Trash your leftmost non-Sign in hand');
  });

  it('capitalises a named type the way the card face does', () => {
    // `kind` is a raw CardType and lowercase; "leftmost sign" read as a typo.
    expect(describeOps(card('dry-grass').toll!)).toContain('leftmost Sign');
  });

  it('calls deck-trashing what it is — damage', () => {
    // `trash` from the deck with no kind named routes to `damagePlayer`. It
    // was printing "Trash 1 of your own", which describes a different rule
    // from the one that runs.
    expect(describeOps([{ op: 'trash', n: 1, from: 'deck', target: 'self' }]))
      .toBe('Take 1 damage');
    expect(describeOps([{ op: 'trash', n: 2, from: 'deck', target: 'all' }]))
      .toBe('Everyone takes 2 damage');
  });

  it('explains both halves in one glossary entry', () => {
    const t = GLOSSARY.trash!;
    expect(t.long).toMatch(/leftmost/);
    expect(t.long).toMatch(/top of your shuffled deck/);
    expect(t.long).toMatch(/boneyard/);
  });
});
