import { ICON_PATHS } from "./iconsgen";
import type { IconName } from "./iconNames";
import omenPng from "./images/omen.webp";

/**
 * Every image in `components/images/`, keyed by filename without extension.
 *
 * A glob rather than an import per card: CardFace's own note says "in
 * production every card wants its own illustration", and a list of forty
 * imports is forty chances for the list and the folder to disagree. Drop
 * `six-gun.png` in and the Six-Gun has art; delete it and the card falls back
 * to its family mark with nothing to clean up.
 *
 * `eager` so the map is a plain object at module load — an async import would
 * make the first paint of every card a loading state.
 */
const ART: Record<string, string> = Object.fromEntries(
  Object.entries(
    import.meta.glob<{ default: string }>("./images/*.{png,webp,jpg,svg}", {
      eager: true,
    }),
  ).map(([path, mod]) => [
    path.replace(/^.*\//, "").replace(/\.[^.]+$/, ""),
    mod.default,
  ]),
);

/** Does this card have an illustration of its own? Asked by `faceOf`. */
export function hasArt(cardId: string): boolean {
  return cardId in ART;
}

/**
 * Icons drawn from an image instead of the generated glyph set.
 *
 * `iconsgen.ts` is generated by `assets/build_icons.py` and says not to edit it
 * by hand, so an artwork icon cannot live there — it lives here, keyed by the
 * same name, and every existing `<Icon name="omen" />` picks it up untouched.
 *
 * **These do NOT inherit `currentColor`.** That is the cost, and it is real:
 * the glyph icons dim with a disabled button, take the ink colour of a Fevered
 * card, and grey out with a discard pile, all for free. A raster does none of
 * that — it is the same pixels everywhere. Worth it for one deliberate piece of
 * art; a set of them would quietly break the rule the whole icon system rests
 * on.
 */
const RASTER: Partial<Record<string, string>> = {
  omen: omenPng,
};

export type { IconName };
export { ICON_GROUPS } from "./iconsgen";

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  /** Pixel size for both width and height. Default 24. */
  size?: number;
  /** Accessible label. Omit for decorative icons (the default). */
  label?: string;
}

/**
 * Every icon inherits `currentColor`, so colour comes from the parent's
 * `color` property - not a prop. That means an icon inside a disabled button
 * or a Fevered card dims automatically with its container.
 *
 *   <span style={{ color: 'var(--ln-dread)' }}><Icon name="whisper" /></span>
 */
export function Icon({ name, size = 40, label, ...rest }: IconProps) {
  // `art:x` is a card's own picture; anything else may still be an override of
  // a glyph, as the Omen is.
  const png = name.startsWith("art:") ? ART[name.slice(4)] : RASTER[name];
  if (png) {
    /*
      An <svg> wrapping an <image>, NOT an <img>.

      This is the whole reason a card's art did not appear. `Icon` is rendered
      in two completely different contexts: HTML flow (buttons, the ticker, the
      glossary) and INSIDE the card's own SVG — `CardFace` draws the field as
      `<g transform=...><Icon /></g>`. An HTML <img> is not a valid SVG child,
      so it silently drew nothing there while working fine everywhere else.

      A nested <svg> is legal in both: valid SVG content, and a normal element
      in HTML. So the component keeps one shape and does not have to know where
      it has been put — which it cannot.

      `preserveAspectRatio` is the SVG spelling of `object-fit: contain`.
    */
    return (
      <svg
        viewBox={`0 0 ${size} ${size}`}
        width={size}
        height={size}
        role={label ? "img" : undefined}
        aria-label={label}
        aria-hidden={label ? undefined : true}
        focusable="false"
        style={{ display: "block", overflow: "visible" }}
      >
        <image
          href={png}
          width={size}
          height={size}
          preserveAspectRatio="xMidYMid meet"
        />
      </svg>
    );
  }
  // An art-only name has no glyph behind it, so this lookup can miss — hence
  // the cast and the null. `ICON_PATHS` is keyed by the generated union only.
  const d = (ICON_PATHS as Record<string, string | undefined>)[name];
  if (!d) return null;
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={1.6}
      strokeLinecap="square"
      strokeLinejoin="miter"
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      focusable="false"
      dangerouslySetInnerHTML={{ __html: d }}
      {...rest}
    />
  );
}

/**
 * Repeat an icon n times - Whisper pips on a Sign, Scars on a board, Menace
 * value on a Threat. Board games count things; this is the common case.
 */
export function IconCount({
  name,
  count,
  size = 16,
  label,
}: {
  name: IconName;
  count: number;
  size?: number;
  label?: string;
}) {
  return (
    <span
      role="img"
      aria-label={label ?? `${count} ${name}`}
      style={{ display: "inline-flex", gap: 2, alignItems: "center" }}
    >
      {Array.from({ length: count }, (_, i) => (
        <Icon key={i} name={name} size={size} />
      ))}
    </span>
  );
}
