// The icon name space, widened past the generated glyphs.
//
// Two constraints meet here and neither is negotiable:
//
//   - `iconsgen.ts` is generated by `assets/build_icons.py` and says not to
//     edit it, so per-card artwork cannot be added to the glyph union.
//   - `icons.ts` is compiled by the ROOT tsconfig (the narration tests reach
//     it), which has no `.png` module declarations and no DOM. So the NAMES
//     have to live somewhere with no asset imports at all.
//
// Hence this file: types only, nothing the root project cannot resolve.

import type { IconName as Glyph } from './iconsgen';

/**
 * A card's own illustration, named `art:<card id>`.
 *
 * A template type rather than a union of ids, so adding art is dropping a file
 * into `components/images/` — no list to keep in step with the folder, and no
 * chance of a name in one and a file in the other. `Icon.tsx` resolves these
 * against a glob of that folder; `hasArt` is how a caller asks whether a
 * particular card has any.
 */
export type ArtIconName = `art:${string}`;

export type IconName = Glyph | ArtIconName;
