// GENERATED by assets/build_icons.py - do not edit by hand.

export const ICON_PATHS = {
  whisper: `<path d='M12.4 12.6a1.4 1.4 0 0 0 1.3-1.5 3.4 3.4 0 0 0-3.6-3.2 5.4 5.4 0 0 0-5 5.8 7.4 7.4 0 0 0 7.9 6.9 9.4 9.4 0 0 0 6.6-3.2'/>`,
  grit: `<path d='M10.4 5.9l3.3 1.4-2.1 2.4-2.2-1.4z' fill='currentColor' stroke='none'/><path d='M16.1 11.4l2.9 2.6-3.4 1.1-.6-2.6z' fill='currentColor' stroke='none'/><path d='M5.6 12.1l2.6-.4.5 2.9-2.4.2z' fill='currentColor' stroke='none'/><path d='M10.9 15.1l3.1 1.9-2.6 2.1-1.9-2z' fill='currentColor' stroke='none'/>`,
  doom: `<circle cx='12' cy='12' r='4.1'/><path d='M12 3.6v2.2M12 18.2v2.2M3.6 12h2.2M18.2 12h2.2M6.1 6.1l1.6 1.6M16.3 16.3l1.6 1.6M17.9 6.1l-1.6 1.6M7.7 16.3l-1.6 1.6'/>`,
  scar: `<path d='M3.9 12.1h16.2'/><path d='M7.4 8.4l2.6 7.4M10 8.4l-2.6 7.4M14 8.4l2.6 7.4M16.6 8.4l-2.6 7.4'/>`,
  grave: `<path d='M7.2 19.6v-8.2a4.8 4.8 0 0 1 9.6 0v8.2z'/><path d='M4.6 19.6h14.8M12 11.4v4.4M10.1 13.3h3.8'/>`,
  kit: `<path d='M5.2 9.8h13.6v9.4H5.2z'/><path d='M5.2 9.8l2.1-4.2h9.4l2.1 4.2'/><path d='M10.7 12.2h2.6v3.4h-2.6z'/>`,
  deed: `<path d='M6.2 4.3h7.9l4 4.1v11.3H6.2z'/><path d='M14.1 4.3v4.1h4'/><path d='M9 12.3h6.1M9 15.2h6.1'/>`,
  sign: `<path d='M12 3.7L20.3 12 12 20.3 3.7 12z'/><path d='M12 7.4v9.2'/><path d='M9.6 10.2h4.8M9.6 13.8h4.8'/>`,
  fevered: `<path d='M12 3.7L20.3 12 12 20.3 3.7 12z'/><path d='M12 3.7l-2.6 6.8 3.9 2.1-2.4 7.7'/>`,
  omen: `<path d='M4.7 10.9c2.6 3.7 12 3.7 14.6 0'/><path d='M6.9 13.1l-1.4 2.9M12 14.2v3.1M17.1 13.1l1.4 2.9'/>`,
  clear: `<circle cx='12' cy='12' r='3.1' fill='currentColor' stroke='none'/><circle cx='12' cy='12' r='6.9'/>`,
  menace: `<path d='M6.9 4.7c1.2 4.1 1.9 8.6 1.1 14.4'/><path d='M12 3.9c1.2 4.4 2 9.2 1.1 15.4'/><path d='M17.1 4.7c1.2 4.1 1.9 8.6 1.1 14.4'/>`,
  street: `<path d='M3.4 8.9h5.1v6.2H3.4zM9.5 8.9h5.1v6.2H9.5zM15.6 8.9h5.1v6.2h-5.1z'/>`,
  marked: `<path d='M8.1 20v-6.6L6.4 10.7a1.1 1.1 0 0 1 1.8-1.2l1.7 2.4V6.2a1.1 1.1 0 0 1 2.2 0v4.9V5.1a1.1 1.1 0 0 1 2.2 0v6V7.4a1.1 1.1 0 0 1 2.2 0v8.4A4.2 4.2 0 0 1 12.4 20z'/>`,
  vessel: `<path d='M6.2 20.4V10.1a5.8 5.8 0 0 1 11.6 0v10.3'/><path d='M3.9 20.4h16.2'/><path d='M9.3 20.4v-7.6a2.7 2.7 0 0 1 5.4 0v7.6z' fill='currentColor' stroke='none'/>`,
  revenant: `<path d='M6.9 15.9v-2.6a5.1 5.1 0 1 1 10.2 0v2.6z'/><path d='M15.6 15.9v3.9H8.4v-3.9'/><path d='M9.1 11.4l2.4 2.4M11.5 11.4l-2.4 2.4M12.5 11.4l2.4 2.4M14.9 11.4l-2.4 2.4'/><path d='M10.2 16.4v3.4M13.8 16.4v3.4'/>`,
} as const;

export type IconName = keyof typeof ICON_PATHS;

export const ICON_GROUPS: Record<string, IconName[]> = {
  track: ["whisper", "grit", "doom"],
  state: ["scar", "grave"],
  object: ["kit", "deed"],
  mark: ["sign", "fevered", "omen"],
  threat: ["clear", "menace", "street"],
  role: ["marked", "vessel", "revenant"],
};
